--------------------------------------------------------
--  File created - Saturday-May-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PEMINJAMAN
--------------------------------------------------------

  CREATE TABLE "PERPUSB"."PEMINJAMAN" 
   (	"TANGGAL_PINJAM" DATE, 
	"TANGGAL_KEMBALI" DATE, 
	"ID" VARCHAR2(20 BYTE), 
	"ISBN" VARCHAR2(20 BYTE), 
	"KET" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PERPUSB.PEMINJAMAN
SET DEFINE OFF;
Insert into PERPUSB.PEMINJAMAN (TANGGAL_PINJAM,TANGGAL_KEMBALI,ID,ISBN,KET,STATUS) values (to_date('13-MAY-17','DD-MON-RR'),to_date('13-MAY-17','DD-MON-RR'),'145314000','9781480177598','-','Y');
Insert into PERPUSB.PEMINJAMAN (TANGGAL_PINJAM,TANGGAL_KEMBALI,ID,ISBN,KET,STATUS) values (to_date('13-MAY-17','DD-MON-RR'),to_date('13-MAY-17','DD-MON-RR'),'145314000','9781138035454','Webservice','Y');
--------------------------------------------------------
--  Constraints for Table PEMINJAMAN
--------------------------------------------------------

  ALTER TABLE "PERPUSB"."PEMINJAMAN" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."PEMINJAMAN" MODIFY ("KET" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."PEMINJAMAN" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."PEMINJAMAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."PEMINJAMAN" MODIFY ("TANGGAL_KEMBALI" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."PEMINJAMAN" MODIFY ("TANGGAL_PINJAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PEMINJAMAN
--------------------------------------------------------

  ALTER TABLE "PERPUSB"."PEMINJAMAN" ADD CONSTRAINT "ID_FK1" FOREIGN KEY ("ID")
	  REFERENCES "PERPUSB"."ANGGOTA" ("ID") ENABLE;
  ALTER TABLE "PERPUSB"."PEMINJAMAN" ADD CONSTRAINT "ISBN_FK2" FOREIGN KEY ("ISBN")
	  REFERENCES "PERPUSB"."BUKU" ("ISBN") ENABLE;
