--------------------------------------------------------
--  File created - Saturday-May-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANGGOTA
--------------------------------------------------------

  CREATE TABLE "PERPUSB"."ANGGOTA" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAMA" VARCHAR2(30 BYTE), 
	"NO_TELEPON" VARCHAR2(20 BYTE), 
	"ALAMAT" VARCHAR2(150 BYTE), 
	"PASSWORD" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PERPUSB.ANGGOTA
SET DEFINE OFF;
Insert into PERPUSB.ANGGOTA (ID,NAMA,NO_TELEPON,ALAMAT,PASSWORD) values ('0','admin','0','0','admin');
Insert into PERPUSB.ANGGOTA (ID,NAMA,NO_TELEPON,ALAMAT,PASSWORD) values ('145314000','Gokong','081000000000','Gunung Siluent','1234');
--------------------------------------------------------
--  DDL for Index ANGGOTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERPUSB"."ANGGOTA_PK" ON "PERPUSB"."ANGGOTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANGGOTA
--------------------------------------------------------

  ALTER TABLE "PERPUSB"."ANGGOTA" ADD CONSTRAINT "ANGGOTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PERPUSB"."ANGGOTA" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."ANGGOTA" MODIFY ("ALAMAT" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."ANGGOTA" MODIFY ("NO_TELEPON" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."ANGGOTA" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "PERPUSB"."ANGGOTA" MODIFY ("ID" NOT NULL ENABLE);
